wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1753190705.988797
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.8.15
      5: 0.13.5
      8:
      - 5
algo:
  desc: null
  value: ppo
batch_size:
  desc: null
  value: 144
device:
  desc: null
  value: cpu
env:
  desc: null
  value: trunkcube-v0
eval_episodes:
  desc: null
  value: 50
eval_freq:
  desc: null
  value: 10000
group:
  desc: null
  value: null
hostname:
  desc: null
  value: 466a645ed566
keep_prev_ckpt:
  desc: null
  value: false
lr:
  desc: null
  value: 0.0001
n_layers:
  desc: null
  value: 3
n_neurons:
  desc: null
  value: 512
noisy_setting:
  desc: null
  value: false
notes:
  desc: null
  value: null
now:
  desc: null
  value: 12
path:
  desc: null
  value: runs/trunkcube-v0/2025_07_22_15_25_04_trunkcube-v0_ppo_t2000000_seed2_466a645ed566_P1M1O/
reduced_sensing:
  desc: null
  value: true
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: null
resume_wandb:
  desc: null
  value: null
reward_threshold:
  desc: null
  value: false
run_path:
  desc: null
  value: null
save_freq:
  desc: null
  value: '10000'
seed:
  desc: null
  value: 2
test_env:
  desc: null
  value: trunkcube-v0
test_episodes:
  desc: null
  value: 100
test_render:
  desc: null
  value: false
timesteps:
  desc: null
  value: 2000000
verbose:
  desc: null
  value: 0
wandb_mode:
  desc: null
  value: online
