wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/train_npdr.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.15
    start_time: 1752141753.376381
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 3
      - 13
      - 14
      - 16
      - 23
      4: 3.8.15
      5: 0.13.5
      8:
      - 5
algo:
  desc: null
  value: ppo
batch_size:
  desc: null
  value: 144
bounds_path:
  desc: null
  value: runs/trunkcube-pyrado-v0/2025_07_08_09_52_33_trunkcube-pyrado-v0_ppo_t2000000_seed0_6748d0f059d0_RJT9B/pyrado_results/
clipping:
  desc: null
  value: null
data:
  desc: null
  value: custom
data_path:
  desc: null
  value: null
device:
  desc: null
  value: cpu
env:
  desc: null
  value: trunkcube-pyrado-v0
eval_episodes:
  desc: null
  value: 50
eval_freq:
  desc: null
  value: 10000
group:
  desc: null
  value: null
inference_only:
  desc: null
  value: false
initial_info_only:
  desc: null
  value: true
lr:
  desc: null
  value: 0.0001
max_iter:
  desc: null
  value: 2
n_layers:
  desc: null
  value: 3
n_neurons:
  desc: null
  value: 512
n_trajectories:
  desc: null
  value: null
no_output:
  desc: null
  value: false
noisy_setting:
  desc: null
  value: true
normalize_posterior:
  desc: null
  value: false
notes:
  desc: null
  value: null
now:
  desc: null
  value: 12
num_eval_samples:
  desc: null
  value: 10
num_sbi_rounds:
  desc: null
  value: 7
num_sim_per_round:
  desc: null
  value: 4000
off_policy:
  desc: null
  value: null
print_map:
  desc: null
  value: false
reduced_sensing:
  desc: null
  value: true
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: null
resume_wandb:
  desc: null
  value: null
reward_threshold:
  desc: null
  value: false
run_path:
  desc: null
  value: results/NPDR_Train
seed:
  desc: null
  value: 1
simulation_batch_size:
  desc: null
  value: 10
test_env:
  desc: null
  value: trunkcube-pyrado-v0
test_episodes:
  desc: null
  value: 100
test_render:
  desc: null
  value: false
timesteps:
  desc: null
  value: 2000000
training_batch_size:
  desc: null
  value: 50
training_only:
  desc: null
  value: true
unmodeled:
  desc: null
  value: null
verbose:
  desc: null
  value: 0
wandb_mode:
  desc: null
  value: online
