wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    code_path: code/train_udr.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.19
    start_time: 1742426859.2919
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 3
      - 13
      - 14
      - 16
      - 19
      - 23
      4: 3.8.19
      5: 0.13.5
      8:
      - 5
algo:
  desc: null
  value: ppo
batch_size:
  desc: null
  value: 144
device:
  desc: null
  value: cpu
env:
  desc: null
  value: trunkcube-v0
eval_episodes:
  desc: null
  value: 50
eval_freq:
  desc: null
  value: 10000
group:
  desc: null
  value: null
hostname:
  desc: null
  value: efce1bc0eb04
lr:
  desc: null
  value: 0.0001
n_layers:
  desc: null
  value: 3
n_neurons:
  desc: null
  value: 512
notes:
  desc: null
  value: null
now:
  desc: null
  value: 12
path:
  desc: null
  value: runs/trunkcube-v0/2025_03_20_00_27_37_trunkcube-v0_ppo_t2000000_seed0_efce1bc0eb04_0IK4G/
reduced_sensing:
  desc: null
  value: true
resume:
  desc: null
  value: false
resume_path:
  desc: null
  value: null
resume_wandb:
  desc: null
  value: null
reward_threshold:
  desc: null
  value: false
run_path:
  desc: null
  value: null
seed:
  desc: null
  value: 0
test_dynamics:
  desc: null
  value: "[[5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01\
    \ 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01\
    \ 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01\
    \ 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02\
    \ 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n\
    \ [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01\
    \ 4.5e+03]\n [5.0e-02 3.0e-01 4.2e-01 4.5e-01 4.5e+03]]"
test_env:
  desc: null
  value: trunkcube-v0
test_episodes:
  desc: null
  value: 100
test_render:
  desc: null
  value: false
timesteps:
  desc: null
  value: 2000000
train_dynamics_names:
  desc: null
  value:
    '0': cubeMass
    '1': frictionCoeff
    '2': trunkMass
    '3': trunkPoissonRatio
    '4': trunkYoungModulus
train_space_bounds:
  desc: null
  value:
  - - 0.005
    - 1.0
  - - 0.01
    - 1.0
  - - 0.005
    - 1.0
  - - 0.4
    - 0.5
  - - 2000.0
    - 7000.0
train_uniform_distr:
  desc: null
  value:
  - - 0.16641170546384493
    - 0.6562070046222812
  - - 0.18852836076846166
    - 0.8859417513938955
  - - 0.015285036630164325
    - 0.6434353459735513
  - - 0.4607430580974189
    - 0.474125522773881
  - - 4232.021213803457
    - 6857.005128207103
unmodeled:
  desc: null
  value: null
verbose:
  desc: null
  value: 0
wandb_mode:
  desc: null
  value: online
